#- path.config: /usr/share/logstash/pipeline/worker-cmdb
#  pipeline.id: worker-cmdb
#- path.config: /usr/share/logstash/pipeline/worker-jenkinsci
#  pipeline.id: worker-jenkinsci
#- path.config: /usr/share/logstash/pipeline/worker-jenkinscdp
#  pipeline.id: worker-jenkinscdp
#- path.config: /usr/share/logstash/pipeline/worker-leadtime
#  pipeline.id: worker-leadtime
#- path.config: /usr/share/logstash/pipeline/worker-users
#  pipeline.id: worker-users
#- path.config: /usr/share/logstash/pipeline/worker-nexus
#  pipeline.id: worker-nexus
#- path.config: /usr/share/logstash/pipeline/worker-gitlab
#  pipeline.id: worker-gitlab
#- path.config: /usr/share/logstash/pipeline/worker-test
#  pipeline.id: worker-test
- path.config: /usr/share/logstash/pipeline/request
  pipeline.id: request